services:
  - type: web
    name: brightwave-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://brightwaveenterprises.online, https://www.brightwaveenterprises.online
