services:
  - type: web
    name: brightwave-website
    env: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn server.app:app
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://brightwaveenterprises.online, https://www.brightwaveenterprises.onlin
